# Generated by Django 2.0.5 on 2018-05-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Тест поста')),
                ('created_at', models.DateTimeField(verbose_name='Создано в')),
                ('published_at', models.DateTimeField(verbose_name='Опубликовано в')),
                ('url_slug', models.CharField(max_length=150, unique=True, verbose_name='URL')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано?')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'db_table': 'posts',
                'ordering': ('-published_at',),
            },
        ),
    ]
